default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password: postgres
 
development:
  <<: *default
  database: journal_app_development
 
test:
  <<: *default
  database: journal_app_test